version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./api:/code/api
      - ./env_variables:/code/env_variables
      - ./requirements.txt:/code/requirements.txt
    networks:
      - backend

networks:
  backend:
    name: backend
    driver: bridge
